name: TinyWorlds
version: '1.0.0'
main: com.github.teraprath.tinyworlds.TinyWorlds
api-version: '1.20'
authors: [TerryGHG]
commands:
  worlds:
    description: Open the Worlds Gui
    permission: tiny.command.worlds